apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "spaces.fullname" . }}
  labels:
    app: {{ template "spaces.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: {{ template "ingressClass" . }}
    nginx.ingress.kubernetes.io/auth-url: {{ default (printf "http://%s-edge-auth.%s.svc.cluster.local:8080/v1/auth" .Release.Name .Release.Namespace ) .Values.ingress.authURL | quote }}
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite (?i)/api/v1/(.*) /v1/$1 break;
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/spaces
            backend:
              serviceName: {{ template "spaces.fullname" . }}
              servicePort: {{ .Values.service.port }}
